### ISSUE TITLE
Allow a dependency to be a URL.

### ISSUE THREAD

**Issue by eobrain** [eobrain/bajel#30]
* Download if newer than target.
* Download to a temporary file, which is what $< and $+ will refer to.

So instead of ...

```yaml
some_target:
  deps:
  - downloaded_file.csv"
  - other_dep
  exec: do_something $< >$@

downloaded_file.csv:
  exec: wget --output-document=$@ https://foo.com/some-url.csv
```

... you could just have ...

```yaml
some_target:
  deps:
  - https://foo.com/some-url.csv
  - other_dep
  exec: do_something $< >$@
```
